### ISSUE TITLE
Module not found: Can't resolve 'react-crop/css'

### ISSUE THREAD

**Issue by jhc1982** [instructure-react/react-crop#25]
I am just trying to get Cropper up and running in a project but cannot seem to get react-crop/css to load.

I have check all dependencies and they are installed ok.

I am using import 'react-crop/css';

Do I need to specify the full path?

**Comment by jhc1982** [comment]
I had a look in node_modules and I cannot see any css folder or file. I can see cropper.css, should I adjust the import to:

` import 'react-crop/cropper.css';`

When I do this I then get the following:

![screen shot 2018-02-06 at 12 23 13 pm 1](https://user-images.githubusercontent.com/525268/35859584-9d7ae872-0b38-11e8-993e-9d1475834960.png)

**Comment by shichongrui** [comment]
I believe that the css is already imported by the module itself. So importing `react-crop` should get you the css without having to import the css directly. Check out https://github.com/instructure-react/react-crop/blob/master/lib/index.src.js#L4

**Comment by jhc1982** [comment]
I gave that a go but no change. I still get the error message as above:

```
TypeError: Cannot read property 'number' of undefined
./node_modules/react-crop/draggable-resizable-box.js
node_modules/react-crop/draggable-resizable-box.js:21
  18 | displayName: 'DraggableResizableBox',
  19 | 
  20 | propTypes: {
> 21 |   aspectRatio: _react2.default.PropTypes.number.isRequired,
  22 |   width: _react2.default.PropTypes.number.isRequired,
  23 |   height: _react2.default.PropTypes.number.isRequired,
  24 |   onChange: _react2.default.PropTypes.func,
```

**Comment by jhc1982** [comment]
I used create-react-app to start the project, but then ejected to use CSS modules. Is there some kind of config that I need to change in this case?

**Comment by shichongrui** [comment]
This module has not been updated to use react v16 yet. The error you are seeing above is because PropTypes are no longer available on the `react` module and are in a separate module now. There is an open pull request to upgrade to react v16 but that doesn't seem to have been updated in a while.

**Comment by jhc1982** [comment]
Ah! That will be the problem then!

Sorry, I should have mentioned the react version when asking.

I appreciate the help
