### ISSUE TITLE
Cropper is not rendering in HTML

### ISSUE THREAD

**Issue by raghavgarg1257** [instructure-react/react-crop#26]
Hey,

Thanks for the package, I am stcuk while rendering the cropper. Below is my code, can you please help?

```js
import React, { Component } from 'react';

let Cropper = null;

export default class UserDetailEdit extends Component {
  
  state = {
    image_src: null
  };
  
  componentDidMount() {
    Cropper = require('react-crop');
  }
  
  uploadFile(e) {
    this.setState({ image_src: e.target.files[0] });
  }
  
  render() {
    return (
      <div>
        {
          this.state.image_src === null || Cropper === null ? (
            <input type="file" onChange={this.uploadFile} />
          ) : (
            <Cropper
              src={this.state.image_src}
              ref={(c) => { this.cropper = c; }}
            />
          )
        }
      </div>
    );
  }
}
```
It is giving me the below error,
> React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

**Comment by shichongrui** [comment]
The render function will be called before `componentDidMount` and since you are pulling in `react-crop` in `componentDidMount`, on your first render `Cropper` will still be null. Why are you requiring `react-crop` in `componentDidMount` instead of importing it at the top of your file?

**Comment by raghavgarg1257** [comment]
I have using SSR in my project because of which I can't require any library at the top of the file which is using browser variables like `window`. See [this issue](https://github.com/reactjs/react-chartjs/issues/57) on another react library, I am following [this comment](https://github.com/reactjs/react-chartjs/issues/57#issuecomment-257117560).

Regarding this,
> on your first render Cropper will still be null

Yes, You are right but on my first render `this.state.image_src` will always be null and hence the `Cropper` will not be executed. Also, I am not rendering Cropper until it is initiated (refer the condition in render method `Cropper === null ? <input /> : <Cropper />`). So I guess, it should work.

Please correct me if anything feels wrong in above explanation, or could be done in better way.

**Comment by shichongrui** [comment]
Ah yes I didn't see that. So that being the case, I'm skeptical that this error is happening because of the Cropper since it will be null and your render function won't render it. Usually this error happens when you are importing/requiring something incorrectly which can happen easily when mixing modules and require. Check where you are importing/requiring UserDetailEdit as that may be the culprit.
